config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'web' do
    root 'orders#index'

    resources :orders do
      resources :services, shallow: true do
        scope module: 'services' do
        
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :services, dependent: :destroy

  validates :customer_name, presence: true
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  belongs_to :order

  validates :name, presence: true
end

app/models/service/category.rb
# frozen_string_literal: true

class Service
  class Category < ApplicationRecord
    validates :name, presence: true
  end
end

app/models/service/provider.rb
# frozen_string_literal: true

class Service
  class Provider < ApplicationRecord
    validates :name, presence: true
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
end

app/controllers/web/orders_controller.rb
# frozen_string_literal: true

class Web::OrdersController < Web::ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find params[:id]
    @services = @order.services.order('created_at DESC')
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(permitted_params)

    if @order.save
      redirect_to root_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @order = Order.find params[:id]
  end

  def update
    @order = Order.find params[:id]

    if @order.update(permitted_params)
      redirect_to root_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])

    if @order.destroy
      redirect_to orders_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def permitted_params
    params.require(:order).permit(:customer_name)
  end
end

app/controllers/web/services/application_controller.rb
# frozen_string_literal: true

class Web::Services::ApplicationController < Web::ApplicationController
end

app/controllers/web/services/categories_controller.rb
# frozen_string_literal: true

class Web::Services::CategoriesController < Web::Services::ApplicationController
end

app/controllers/web/services/providers_controller.rb
# frozen_string_literal: true

class Web::Services::ProvidersController < Web::Services::ApplicationController
end

app/controllers/web/services_controller.rb
# frozen_string_literal: true

class Web::ServicesController < Web::ApplicationController
  def show
    @service = Service.find params[:id]
  end

  def new
    @order ||= Order.find params[:order_id]
    @service = Service.new
  end

  def create
    @order ||= Order.find params[:order_id]
    @service = @order.services.build(permitted_params)

    if @service.save
      redirect_to @order, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def permitted_params
    params.require(:service).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100 lang="#{I18n.locale}"
  head
    = render 'layouts/shared/head'
  body.d-flex.flex-column.h-100
    = render 'layouts/shared/nav'
    main.container
      = render_flash_messages dismissible: true
      = yield
    = render 'layouts/shared/footer'

app/views/layouts/shared/_footer.html.slim
footer.mt-auto.py-3.bg-light

app/views/layouts/shared/_head.html.slim
= stylesheet_pack_tag 'application', media: 'all'
= javascript_pack_tag 'application', id: 'application'
meta charset="utf-8"
meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
= csp_meta_tag
= csrf_meta_tags
= yield :meta
/ title = title
= yield :js

app/views/layouts/shared/_nav.html.slim
header.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom.text-black.navbar-light
    nav.navbar.navbar-expand-md.me-auto
      = link_to t('.home'), root_path, class: 'navbar-brand'
      button.navbar-toggler[
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      .collapse.navbar-collapse id="navbarCollapse"
        ul.navbar-nav.ms-auto.mb-2.mb-md-0
    ul.nav.nav-pills

app/views/web/orders/_form.html.slim
= simple_form_for @order, html: { class: 'my-5' } do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :customer_name

  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

app/views/web/orders/edit.html.slim
.p-4.mt-4.align-items-center.border.shadow.bg-white.rounded-3
  .p-3.p-lg-4.pt-lg-0
    .mb-4
      h1.mt-5
        = t('.title')
      hr
      = render 'form'
      hr
      = link_to t('back'), :back, class: 'btn btn-outline-primary'

app/views/web/orders/index.html.slim
.p-4.mt-4.align-items-center.border.shadow.bg-white.rounded-3
  .p-3.p-lg-4.pt-lg-0
    .mb-4
      h1.mt-5
        = t('.title')
      hr
      = link_to t('.new_order'), new_order_path, class: 'my-4 btn btn-primary'
      - if @orders.present?
        table.table.table-striped.table-hover.mb-5
          thead
            tr
              th{ scope: :col } #
              th{ scope: :col } = t('.customer_name')
              th{ scope: :col } = t('.created_at')
              th{ scope: :col }
          tbody
            - @orders.each_with_index do |order, i|
              tr
                th{ scope: :col } = i + 1
                td = order.customer_name
                td = order.created_at.strftime('%b %d, %Y %H:%M')
                td.d-flex
                  .me-4 = link_to t('show'), order
                  .me-4 = link_to t('edit'), edit_order_path(order)
                  = link_to t('destroy'), order, data: { confirm: t('warning_destroy') }, method: :delete

app/views/web/orders/new.html.slim
.p-4.mt-4.align-items-center.border.shadow.bg-white.rounded-3
  .p-3.p-lg-4.pt-lg-0
    .mb-4
      h1.mt-5
        = t('.title')
      hr
      = render 'form'
      hr
      = link_to t('back'), :back, class: 'btn btn-outline-primary'

app/views/web/orders/show.html.slim
.p-4.mt-4.align-items-center.border.shadow.bg-white.rounded-3
  .p-3.p-lg-4.pt-lg-0
    .mb-4
      h1.mt-5
        = @order.customer_name
      hr
      = link_to t('.new_service'), new_order_service_path(@order), class: 'my-4 btn btn-primary'
    p
      strong.me-2
        = t('.created_at')
      = @order.created_at.strftime('%b %d, %Y %H:%M')
    hr
    - if @order.services.present?
      table.table.table-striped
        thead
          tr
            th{ scope: :col } #
            th{ scope: :col } = t('.name')
            th
        tbody
          - @order.services.each_with_index do |service, i|
            tr
              th{ scope: :col } = i + 1
              td = service.name
              td.d-flex
                .me-4 = link_to t('show'), service_path(service)
                .me-4 = link_to t('edit'), edit_service_path(service)
                = link_to t('destroy'), service_path(service), data: { confirm: 'Are you sure?' }, method: :delete

app/views/web/services/new.html.slim
.p-4.mt-4.align-items-center.border.shadow.bg-white.rounded-3
  .p-3.p-lg-4.pt-lg-0
    .mb-4
      h1.mt-5
        = t('.title')
      hr
      = simple_form_for @service, url: order_services_path(@order), html: { class: 'my-5' } do |f|
        = f.error_notification
        = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

        = f.input :name

        = f.button :submit, class: 'btn btn-success mt-4 btn-block'
      hr
      = link_to t('back'), :back, class: 'btn btn-outline-primary'

app/views/web/services/show.html.slim
.p-4.mt-4.align-items-center.border.shadow.bg-white.rounded-3
  .p-3.p-lg-4.pt-lg-0
    .mb-4
      h1.mt-5
        = @service.name
      hr
    p
      strong.me-2
        = t('.created_at')
      = @service.created_at.strftime('%b %d, %Y %H:%M')
    hr
    - if @service.present?
      table.table.table-striped
        thead
          tr
            th{ scope: :col } #
            th{ scope: :col } = t('.name')
            th
        tbody